import { Open_Sans } from "next/font/google";
import { Anton } from "next/font/google";
import { Lato } from "next/font/google";
import "./globals.css";
import { ShopProvider } from "@/context/ShopContext";
import { CategoryProvider } from "@/context/CategoryContext";
import Header from "@/components/header/Header";
import { Toaster } from "@/components/ui/sonner";
import BottomMenu from "@/components/BottomMenu";
import { Provider } from "./provider";

const open_Sans = Open_Sans({
	variable: "--font-open-sans",
	subsets: ["latin"],
});
const lato = Lato({
	variable: "--font-lato",
	subsets: ["latin"],
	weight: "400",
});
const anton = Anton({
	variable: "--font-anton",
	weight: "400",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${anton.variable} antialiased`}>
				<ShopProvider>
					<CategoryProvider>
						<Provider>
							<Header />
							<main className="pb-20">{children}</main>
							<BottomMenu />
							<Toaster
								toastOptions={{
									className: "bg-primary text-white",
								}}
							/>
						</Provider>
					</CategoryProvider>
				</ShopProvider>
			</body>
		</html>
	);
}
