import { Open_Sans } from "next/font/google";
import { Anton } from "next/font/google";
import "./globals.css";
import { ShopProvider } from "@/context/ShopContext";
import Header from "@/components/header/Header";
import { Toaster } from "@/components/ui/sonner";

const open_Sans = Open_Sans({
	variable: "--font-open-sans",
	subsets: ["latin"],
});
const anton = Anton({
	variable: "--font-anton",
	weight: "400",
	subsets: ["latin"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${anton.variable} antialiased`}>
				<ShopProvider>
					<Header />
					<main>{children}</main>
					<Toaster
						toastOptions={{
							className: "bg-primary text-white",
						}}
					/>
				</ShopProvider>
			</body>
		</html>
	);
}
